### PR TITLE
feat(ShareImagePreview): warn users of padding overflow in ShareImage…

### PR DESCRIPTION
**Pull request by ovbm**
https://user-images.githubusercontent.com/20746301/115880722-532ea380-a44b-11eb-99a0-f7cd4f6d4298.mov

(only shows red background in preview mode)

### CODE REVIEW

**Comment by annatraussnig** [comment]
Great idea. 
However: the implementation feels very dramatic and I can see people freaking out at the sigh of this red-blood ocean. How about toning it down a little (e.g. showing a dashed border instead of a red background) and adding a description of the problem (to begin with, at least – I imagine this could be removed once everyone is familiar with the tool)?

**Comment by ovbm** [comment]
true, will make an iteration once I get the backends running on my M1

**Comment by ovbm** [comment]
New and improved, less in your face and with a not offering solutions to get rid of the warning:

I reduced the default font size to 56, because 60 would overflow immediately on some images.

**Comment by ovbm** [comment]
@annatraussnig for your consideration :D

**Review by annatraussnig — APPROVED** [review]
LGTM – let's just test the actual generated share image (`ARTICLE_URL?extract=share`) before deploying to master

**Pull request merged**
