### PR TITLE
fix(TeaserEmbedComment): remove whitespace for multiple embeds in a row

### PR DESCRIPTION
**Pull request by annatraussnig**
### Before
Screenshot 2021-10-04 at 11 43 33

### After
Screenshot 2021-10-04 at 11 42 01

### CODE REVIEW

**Review by ovbm — APPROVED** [review]
It feels weird not doing this with preuso-selectors and css, but It doesn't seem to be possible...

**Comment by annatraussnig** [comment]
I'm so dead into these schemas atm that it didn't even cross my mind. I'll check if it's possible tomorrow morning 😄

**Comment by annatraussnig** [comment]
So with `loaders` and stuff, the className and css would have to be in the template. Which feels kinda weird.

**Pull request merged**
