### PR TITLE
Improve method to persist draft-values for input fields inside discussions

### PR DESCRIPTION
**Pull request by trm217**
## Description

This pull-request aims to solve an issue caused by a shared draft for all inputs on a discussion. Now each input is saved on it's own and can thus be saved without overlap.

### Before

https://user-images.githubusercontent.com/30313631/134655241-377cd854-73fc-47b2-a798-78800b9a08cc.mov

### After

https://user-images.githubusercontent.com/30313631/134655493-5e14b998-908e-45f7-ac82-9ba6b660bc9d.mov

(at 6 seconds you see how previous drafts get migrated)

### CODE REVIEW

**Comment by trm217** [comment]
fixed #362

**Comment by trm217** [comment]
closes #375 
@panmau thanks a lot for your effort 👍🏻

**Review by tpreusse — COMMENTED** [review]
Awesome. Generally looks good to me, a few comments to simplify the code a bit.

One thing that is missing in the «after» video: a list of all drafts around the root compose and or automatically opening the reply compose when it has a draft. But I assume that we'll be part of a future frontend PR? To avoid an additional PR you probably want to expose `loadStoredDraftsObject` in `src/lib.js` (currently `commentComposerStorageKey` is exposed).

**Review by tpreusse — APPROVED** [review]

**Comment by panmau** [comment]
@trm217 Thanks for getting this over the finish line! :tada:

**Pull request merged**
