### PR TITLE
fix(inQuotes): fix replaceAll not supported in FF

### PR DESCRIPTION
**Pull request by annatraussnig**
my bad…

### CODE REVIEW

**Comment by ovbm** [comment]
I didn't know that XD

**Review by ovbm — APPROVED** [review]

**Comment by annatraussnig** [comment]
No wait, it is https://caniuse.com/?search=replaceAll… it was working in the SG docs, but not in server side rendering in the frontend (got `replaceAll is not a function`). Maybe @tpreusse knows something I don't.

**Comment by tpreusse** [comment]
@annatraussnig not supported in (our) node js version yet:
```
$ node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> ''.replace
[Function: replace]
> ''.replaceAll
undefined
> 
```
But would also be a problem for older browsers, even older Chromes and Mobile Safaris.

**Pull request merged**
